
version: 2

models:
  - name: Powerlifting_Name_Weight_V
    description: "Name of the power lifter mentioned in the sports dataset"
    columns:
      - name: MeetID 
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: Name
        description: 'name of the power lifter'
      - name: BodyweightKg
        description: 'this is the bodyweight of the powerlifter'
        data_tests:
          - not_null    
  - name: my_test_model_meetid_Raw_V
    description: "Name of the power lifter mentionedin the sports dataset"
    columns:
      - name: MeetID 
        description: "The primary key for this table"