version: 2

models:
  - name: Powerlifting_Name_Weight_V
    description: This table  Powerlifting_Name_Weight_V for meets

    columns:
      - name: meetid
        description: This is a unique identifier for a customer
        tests:
          - not_null

      - name: MeetTown
        description: This is meeting town.

      - name: UK_date
        description: This is for the UK date.