version: 2

models:
  - name: Powerlifting_Name_Weight_V
    description: 'This table  Powerlifting_Name_Weight_V for meets'

    columns:
      - name: meetid
        description: 'This is a unique identifier for a customer'
        tests:
          - not_null

      - name: MeetTown
        description: 'This is meeting town'

      - name: UK_date
        description: 'This is for the UK date'

      - name: Name
        description: 'This is for the Name column'
        tests: 
          - not_null

      - name: Sex
        description: 'The gender of the athlete M or F'
        tests:
          - accepted_values:
              values: ['M', 'F']

      - name: Equipment
        description: 'Type of Lift'
        tests:
          - accepted_values:
              values: ['Raw']
              
          
              